apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: flaskapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_INSTANCE_NAME
          value: mysql
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: 172.68.1.2
        - name: MYSQL_PORT_3306_TCP_PORT
          value: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app
  labels:
    app: flask
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: flask
  type: LoadBalancer